lsst-it/lsst-control

Puppetfile
site/profile/manifests/it/monitoring.pp

Options needs now to be an array

Monitoring update

---

Puppetfile

resolves:
ERROR         -> Unable to manage Puppetfile content 'tuned': Could not resolve desired ref 'topic/fix_error_on_tuned_version_fact' and no default provided

revert tuned mod to forge version

---

site/profile/manifests/core/telegraf.pp

This commit renames the telegraf user and database to match the defaults, and fixes up some bad outputs.
Note that there's a matching private Hiera PR.

maint: fixup telegraf configuration

---

hieradata/site/ls.yaml

Removing summit's future graylog instance, adding the GKE one and reordering the ntp clock

It 2108 syslog

---

hieradata/org/lsst/role/archive-dualhomed.yaml

Completely replaced by profile::core::common

fix usage of profile::comcam::common

---

hieradata/org/ncsa/role/puppet_master.yaml
hieradata/site/npcf/cluster/deploy-test.yaml

for ncsa developers to test puppet changes
Allow sudo for lsst_level1_adm
New hiera file in site/npcf/cluster/
Allow ssh from bastion on puppet_master nodes
Add missing colon to sudo::configs

IT-2184 New cluster "deploy-test-ncsa"

---

hieradata/cluster/comcam-ccs.yaml

Changes for comcam-software 1.0.5 (see https://confluence.lsstcorp.org/display/LSSTCOM/ComCam+software+releases)

comcam-software-1.0.5

---

hieradata/cluster/antu.yaml

This reverts commit 7072c0bde09ec6367cf842281600af9cee688899.

Revert "increase antu primary interface mtu to 9000"

---

hieradata/org/lsst.yaml
hieradata/site/cp.yaml
hieradata/site/dev.yaml
hieradata/site/ls.yaml
hieradata/site/tu.yaml
site/profile/manifests/core/common.pp

quick fixup to solve adding dev and setting tuc to false

adding boolean for install, not installing in tu.

---

Puppetfile
hieradata/org/lsst/role/foreman.yaml
hieradata/org/lsst/role/puppetdb.yaml
hieradata/site/dev/role/foreman.yaml
hieradata/site/ls/role/foreman.yaml
hieradata/site/tu/role/foreman.yaml
site/profile/manifests/core/common.pp
site/profile/manifests/core/puppet_master.pp

Note that foreman-proxy management is not included.

puppetdb + basic puppetserver/foreman management

---

hieradata/org/lsst/role/perfsonar.yaml
hieradata/org/lsst/role/rke.yaml
site/profile/manifests/core/common.pp

Note that this may cause currently active nodes to reboot.

reboot node if selinux state is incorrect

---

site/profile/manifests/core/icinga_master.pp

This reverts commit 5317c3ca0b461a93b557f30f19b7b01658823346.

Revert "remove force deploy, add director daemon"

---

hieradata/site/cp.yaml
hieradata/site/cp/role/foreman.yaml
hieradata/site/cp/role/hypervisor.yaml

Site modifications, vlans relocation, enable monitoring and syslog forwarding

IT-2484: Summit Network Normalization

---

hieradata/org/ncsa.yaml
hieradata/org/ncsa/role/headerservice.yaml
hieradata/site/nts.yaml

Use repo-nexus.lsst.org/nexus/repository/ts_yum_private for OpenSplice
update ospl_version, ts_idl_version, ts_dds_version, ts_salobj_version

LSST-3559 updates for private access to sal2 yumrepo

---

hieradata/node/dns1.tuc.lsst.cloud.yaml
hieradata/node/dns2.tuc.lsst.cloud.yaml
hieradata/node/dns3.tu.lsst.org.yaml
hieradata/org/lsst.yaml
hieradata/site/cp.yaml
hieradata/site/cp/role/foreman.yaml
hieradata/site/dev.yaml
hieradata/site/ls.yaml
hieradata/site/ls/role/foreman.yaml
hieradata/site/tu.yaml
hieradata/site/tu/role/dnscache.yaml
hieradata/site/tu/role/foreman.yaml
tests/yamllint.sh

To bring tu better into sync with ls/dev/cp.

add dns3.tu + update tu dns/dhcp/ntp config

---

hieradata/org/lsst/role/icinga-master.yaml
site/profile/manifests/icinga/agent.pp
site/profile/manifests/icinga/master.pp
site/profile/manifests/icinga/plugins.pp
site/profile/manifests/icinga/resources.pp

Add all checks that currently mrtg is doing to comcam hosts to icinga instance.

IT-2472: mrtg to icinga

---

hieradata/site/cp/role/foreman.yaml

As we are now planning to allocate multus IPs via dhcp.

change 139.229.170.0/24 dhcp pool to .64 - .128 (~/26)

---

Puppetfile
hieradata/node/bastion1.cp.lsst.org.yaml
hieradata/node/eas-hvac01.cp.lsst.org.yaml
hieradata/node/hvac01.cp.lsst.org.yaml
hieradata/node/net-dx.cp.lsst.org.yaml
hieradata/org/lsst/role/bastion.yaml
hieradata/org/lsst/role/hexrot.yaml
hieradata/org/lsst/role/m1m3.yaml
hieradata/org/lsst/role/m2.yaml
site/profile/manifests/core/common.pp
site/profile/manifests/core/net_dx.pp
site/profile/manifests/core/x2go_agent.pp

Configuration of hvac01 node + x2go agent profile by Heinrich

It 2751/hvac01 node

---

Puppetfile

This changes a temperature warning threshold.

Bump lsst/ccs_monit to v0.1.2

---

Puppetfile
hieradata/cluster/auxtel-ccs.yaml
hieradata/node/atsccs1.cp.lsst.org.yaml
hieradata/node/atsdaq1.cp.lsst.org.yaml
hieradata/node/atshcu1.cp.lsst.org.yaml
hieradata/org/lsst.yaml
hieradata/org/lsst/role/atsccs.yaml
hieradata/org/lsst/role/atsdaq.yaml
site/profile/files/ccs/clustershell/auxtel-local.cfg
site/profile/files/ccs/sudo/ccs-sudoers-services
site/profile/manifests/ccs/common.pp

These are the changes for management of CCS on auxtel hosts. They have been tested on the auxtel ccs hosts.
I don't believe there should be any effect on non-auxtel hosts.

IT-2820: auxtel ccs

---

Puppetfile
hieradata/cluster/comcam-ccs.yaml
hieradata/node/comcam-mcm.cp.lsst.org.yaml
hieradata/org/lsst/role/ccs-mcm.yaml

This will enable management of CCS SAL on comcam-mcm, as per https://jira.lsstcorp.org/browse/IT-2613

Comcam mcm sal

---

Puppetfile

This just adds a config file /etc/tmpfiles.d/ccs-ospl.conf

Bump ccs_sal module version

---

hieradata/org/ncsa.yaml

Update yum_pointers in NCSA pakrat repos for OS updates during June 2021 PM

IT-3022 bump NCSA pakrat snapshot to 2021-06-16-1623878701

---

hieradata/site/tu/role/hypervisor.yaml

The value set in hiera was wrong and this was exposed by IT-1657
removing the unmanaged keys.

(tu) fix hypervisor foreman ssh pubkey

---

hieradata/cluster/andes.yaml
hieradata/cluster/antu.yaml
hieradata/cluster/pillan.yaml
hieradata/cluster/vk8s.yaml
hieradata/org/lsst/role/amor.yaml
hieradata/org/lsst/role/archiver.yaml
hieradata/org/lsst/role/docker-compose.yaml
hieradata/org/lsst/role/hexrot.yaml
hieradata/org/lsst/role/k3s.yaml
hieradata/org/lsst/role/rke.yaml
hieradata/site/cp/cluster/rancher.yaml
hieradata/site/ls/cluster/rancher.yaml
hieradata/site/tu/cluster/rancher.yaml

This will upgrade all systems to the default docker version, currently
`19.03.15`.

rm all explicit docker version strings

---

Puppetfile
hieradata/cluster/auxtel-ccs.yaml
hieradata/cluster/comcam-ccs.yaml
hieradata/cluster/pathfinder-ccs.yaml
hieradata/node/comcam-mcm.cp.lsst.org.yaml

Update comcam and auxtel CCS software.

It 3026/comcam auxtel software

---

hieradata/node/auxtel-archiver.tu.lsst.org.yaml

provision auxtel-archiver.tu

---

Puppetfile
hieradata/cluster/auxtel-ccs.yaml
hieradata/cluster/comcam-ccs.yaml
hieradata/node/atsccs1.cp.lsst.org.yaml

This is deployed on comcam and auxtel. and needs to be merged so it can be deployed on tucson test stand

It 3204/comcam software

---

site/profile/manifests/ccs/cfs.pp
site/profile/manifests/ccs/common.pp

Ref https://jira.lsstcorp.org/browse/IT-3361

Install /usr/local/bin/cfs on ccs hosts

---

hieradata/cluster/auxtel-ccs.yaml
hieradata/cluster/comcam-ccs.yaml

This change was applied on all comcam/auxtel nodes and should be merged to master.

It 3493/comcam auxtel xml10.2

---

Puppetfile

add stm/debconf 4.1.0

---

hieradata/common.yaml

In my previous pull request, I somehow forgot to actually change the source URL. :(

hiera: actually change source url for ccs packages to nexus

---

spec/fixtures/hieradata/common.yaml

To prepare for future additional test keys.

(fixtures) sort private hiera keys

---

Puppetfile

(Puppetfile) bump lsst/rke to 1.1.0

---

hieradata/node/comcam-lion03.cp.lsst.org.yaml

As requested in
https://lsstc.slack.com/archives/CLPAZR5D2/p1660748628379059?thread_ts=1660744899.808519&cid=CLPAZR5D2

hiera: add ccs pathfinder and hexvalves services on comcam-lion03

---

hieradata/site/ls/role/rke.yaml

We needed to bump RKE version to upgrade clusters on LS

Bump rke version to 1.3.12

---

metadata.json
spec/spec_helper.rb

(spec) test roles against AlmaLinux 8

---

hieradata/role/ccs-mcm.yaml

To something that actually exists, ref eg
https://lsstc.slack.com/archives/C01270EHCQ3/p1667925293321179

hiera: update the source URL for CCSWebTrending.war

---

Puppetfile
site/profile/manifests/ts/rpi.pp
spec/classes/ts/rpi_spec.rb

To pickup a fix for missing grub_version fact.

(rpi role) fix auditd & docker package problems

---

Puppetfile

To pickup this PR: 
- https://github.com/simp/pupmod-simp-auditd/pull/165

(Puppetfile) bump simp/auditd to 9777116

---

Puppetfile

(Puppetfile) bump simp/auditd to 022b80c

---

Puppetfile
hieradata/cluster/pillan/osfamily/RedHat/major/9.yaml
hieradata/common.yaml
hieradata/node/pillan08.tu.lsst.org.yaml
hieradata/role/rke/osfamily/RedHat/major/9.yaml
site/profile/manifests/core/common.pp
site/profile/manifests/core/nm_dispatch.pp
site/profile/manifests/nm.pp
site/profile/manifests/nm/connection.pp
spec/classes/core/common_spec.rb
spec/classes/core/nm_dispatch_spec.rb
spec/classes/nm_spec.rb
spec/defines/nm/connection_spec.rb
spec/hosts/roles/rke_spec.rb
spec/spec_helper.rb

Depends on:
- #699 
- #700 
- #701 
- #702 
- #703 
- #704 
- #706 
- #707 
- #708 
- #709 
- #710 
- #711 
- #712 
- #713

(rke role) add EL9 support

---

hieradata/node/auxtel-daq-mgt.cp.lsst.org.yaml
hieradata/role/daq-mgt.yaml
spec/hosts/roles/daq_mgt_spec.rb

Update auxtel-daq-mgt to DAQ release R5-V5.0

Update auxtel-daq-mgt release to R5-V5.0

---

hieradata/cluster/yagan.yaml
hieradata/cluster/yagan/role/rke.yaml
spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb

(yagan cluster) add lhn subnet
