lsst-it/lsst-control

- Puppetfile
- site/profile/manifests/default.pp
This pull request updates the classes needed for gs-graylog-node-01 to use the `profile::it::graylog` class. This class was in use before the node was migrated to foreman, and having a little bit of Puppet management is better than no management at all.
> Update puppet code for `profile::it::graylog` application on gs-graylog-node-01

- site/profile/manifests/core/common.pp
This commit manages the rsyslog package and configuration for all corecp
nodes.
> profile::core::common: add rsyslog class

- Puppetfile
This adds the ufw module for dimm.cp.lsst.org, which is presently running Puppet.
This host will eventually be rebuilt (presumably using CentOS) so we should plan
on porting the ufw rules into firewalld when that switch happens.
Fixes IT-1536.
> dimm.cp.lsst.org: add ufw module

- Puppetfile
- site/profile/manifests/core/nfsclient.pp
- site/profile/manifests/core/nfsserver.pp
This pull request adds an NFS module for managing nfs exports and mounts, and
adds in some shims in our profile module to define NFS exports and mounts in
hiera.
I propose that we fork the derdanne/nfs module, apply some fixups, and inject
the hiera resource creation directly into the module. We can push these changes
upstream.
> IT-1686: add NFS module, nfs profile

- hiera.yaml
This commit switches the Hiera hierarchy to use organizational defaults
as the global layer, rather than a shared `common.yaml`. This change
ensures that we're deliberate about the scope of shared configuration
settings across NCSA and LSST.
> IT-1706: switch common layer to org layer

- hieradata/cluster/corecp/role/ipamaster.yaml
- hieradata/cluster/corecp/role/ipareplica.yaml
- hieradata/cluster/coretuc/role/ipamaster.yaml
- hieradata/cluster/coretuc/role/ipareplica.yaml
- hieradata/org/lsst/role/ipamaster.yaml
- hieradata/org/lsst/role/ipareplica.yaml
We aren't doing anything interesting in the cluster specific IPA
configurations. This commit flattens them into the role definition.
> maint: flatten IPA hierarchy

- hieradata/site/cp.yaml
- hieradata/site/ls.yaml
We should prefer using DNS records over straight IP addresses as a
common convention so that we can migrate hosts between subnets, add
multiple A records for services that have multiple providers, redirect
services to a single host, etc.
> maint: use a CNAME for the NTP server

- hieradata/org/lsst/role/rke.yaml
Add  bash completion module, and works for system native packages (such as systemctl, journalctl, ls....) but not for kubectl. In order for kubectl autocompletion to work we need to run "kubectl completion bash >/etc/bash_completion.d/kubectl". This is not complete and is going to be approach in the next PR.
> Add "bash completion" and "bash completion extras"

- Puppetfile
Due to the augeas sysctl provider conflicting with the parsed provided
from duritong/sysctl.
> disable herculesteam/augeasproviders_sysctl

- hieradata/org/ncsa.yaml
- hieradata/org/ncsa/role/archiver.yaml
- hieradata/site/npcf.yaml
- hieradata/site/nts.yaml
- site/profile/manifests/docker.pp
Create a generic docker profile
```
profile::docker
```
that can be included in any role. This is essentially a copy of:
```
hieradata/org/lsst/role/docker-compose.yaml
```
that splits the `include`s into the profile and the data into hiera.
> IT-1860 general docker profile

- hieradata/org/lsst.yaml
In 125707a we pushed the global rsyslog configuration to the LSST
organization level which rewrote the tucson rsyslog.conf files, but we
didn't add client actions, which disabled logging to /var/log/* at
Tucson. This commit resolves the issue by pushing default configuration
at the organziation level; this configuration will be overridden on a
site-specific basis.
> IT-1954: set default rsyslog client log actions

- hieradata/org/lsst/role/foreman.yaml
Puppet uses abstract type definitions to prevent types from leaking between
different Puppet environments, but require an additional generation step for
them to be loadable by Puppet. This modifies r10k to perform that regeneration
when deploying an environment.
> IT-1454: regenerate types when r10k deploys modules

- Puppetfile
- hieradata/node/gs-telegraf-node-01.cp.lsst.org.yaml
- site/profile/manifests/core/common.pp
- site/profile/manifests/core/puppet_master.pp
- site/profile/manifests/core/telegraf.pp
This pull request reimplements telegraf as a monitoring agent on Puppet hosts.
TODO:
> IT-1480: reimplement telegraf

- Puppetfile
- site/profile/manifests/core/common.pp
- site/profile/manifests/core/hardware.pp
This pull request installs ipmitool on hardware that has an IPMI
implementation. For now this is restricted to PowerEdge servers but can expand
as additional server manufacturers are used.
> IT-2081: Install ipmitool on all poweredge servers

- hieradata/org/lsst/role/rke.yaml
`ipmitool` is automatically installed on all poweredge servers by
default in profile::core::hardware.
> maint: remove ipmitool from RKE profile

- .settings/com.puppetlabs.geppetto.pp.dsl.PP.prefs
Geppetto was an Eclipse based IDE for Puppet and has been deprecated for
years. This commit removes configuration needed for that editor.
> maint: remove obsolete geppetto settings

- site/profile/manifests/core/telegraf.pp
The telegraf user can only write to the "telegraf" database and doesn't have
rights to create the DB.
> maint: don't create influx telegraf database

- site/profile/manifests/core/telegraf.pp
By default the telegraf module doesn't purge unmanaged plugin
configurations in `/etc/telegraf/telegraf.d`. This commit reconfigures
the telegraf module to purge unmanaged configs so that deleting a
plugin from Puppet will remove the plugin.
> IT-2104: remove unmanaged telegraf inputs and outputs

- site/profile/manifests/core/telegraf.pp
The conntrack kernel module isn't loaded on all of our nodes and at
present we don't have a need to monitor conntrack statistics. This
commit drops the input plugin from telegraf; we can re-add it when we
need it.
> maint: remove conntrack plugin from telegraf

- hieradata/org/ncsa.yaml
Admin group was renamed.
Remove duplicate group from sssd (since it's added by sshd)
> Update ncsa ldap group names

- Puppetfile
- hieradata/org/lsst/role/comcam-fp.yaml
- hieradata/site/ls/role/comcam-fp.yaml
```
Notice: /Stage[main]/Dhcp/Concat[/etc/dhcp/dhcpd.conf]/File[/etc/dhcp/dhcpd.conf]/content: 
--- /etc/dhcp/dhcpd.conf	2019-10-08 17:00:28.427861509 +0000
+++ /tmp/puppet-file20200430-413113-1o2zor8	2020-04-30 20:41:57.030150545 +0000
@@ -1,8 +1,16 @@
-
omapi-port 7911;
-log-facility local7;
+default-lease-time 43200;
+max-lease-time 86400;
+
+
+not authoritative;
+
+
+ddns-update-style none;
+
+option ntp-servers none;
allow booting;
allow bootp;
@@ -11,39 +19,23 @@
option fqdn.rcode2            255;
option pxegrub code 150 = text ;
-# Bootfile Handoff
-#option architecture code 93 = unsigned integer 16 ;
-#if option architecture = 00:06 {
-#  filename "grub2/shim.efi";
-#} elsif option architecture = 00:07 {
-#  filename "grub2/shim.efi";
-#} elsif option architecture = 00:09 {
-# …
```
> manage DAQ network dhcpd

- hieradata/node/comcam-fp01.ls.lsst.org.yaml
- hieradata/site/ls/role/comcam-fp.yaml
- site/profile/manifests/ccs/daq_interface.pp
```
--- /etc/sysconfig/network-scripts/ifcfg-em2	2019-07-31 16:53:26.914856726 +0000
+++ /tmp/puppet-file20200501-41574-1325zdt	2020-05-01 19:57:23.406035275 +0000
@@ -1,18 +1,11 @@
-TYPE=Ethernet
-PROXY_METHOD=none
-BROWSER_ONLY=no
-BOOTPROTO=none
-DEFROUTE=yes
-IPV4_FAILURE_FATAL=no
-IPADDR=10.0.0.1
-PREFIX=24
-IPV6INIT=no
-IPV6_AUTOCONF=no
-IPV6_DEFROUTE=no
-IPV6_FAILURE_FATAL=no
-IPV6_ADDR_GEN_MODE=stable-privacy
-NAME=em2
-UUID=45e47725-021d-4808-9fbe-3d4978528bb6
-DEVICE=em2
-ONBOOT=yes
-
+# File Managed by Puppet
+DEVICE="em2"
+BOOTPROTO="none"
+ONBOOT="yes"
+TYPE="Ethernet"
+USERCTL="no"
+PEERDNS="no"
+PEERNTP="no"
+IPADDR="10.0.0.1"
+DEFROUTE="no"
+IPV6INIT="no"
```
> add comcam-sm interface/hosts to comcam-fp01

- hieradata/org/ncsa.yaml
- hieradata/org/ncsa/role/default.yaml
- hieradata/site/npcf/cluster/deploy-test.yaml
- site/profile/data/common.yaml
- site/profile/manifests/ncsa/allow_sudo.pp
- site/profile/manifests/ncsa/system_authnz.pp
Add profile::ncsa::allow_sudo
...combines setup for access.conf and sudoers in one place
Move lsst_admin_ncsa sudo access to use profile::ncsa::allow_sudo
...was in sudo::configs (global content)
Remove lsst_admin_ncsa from system_authnz::access::access_allow
...will now be taken care of by profile::ncsa::allow_sudo
Allow_sudo access for lsst_level1_adm on nodes in deploy-test cluster
Allow ssh from bastion in default role
> IT-2206 add profile::ncsa::allow_sudo

- .gitignore
- Puppetfile
- hieradata/org/lsst.yaml
- hieradata/org/lsst/role/comcam-arctl.yaml
- hieradata/site/ls/role/comcam-arctl.yaml
- site/profile/manifests/archive/rabbitmq.pp
The initial comcam-arctl role:
* installs rabbitmq 3.8.3 + manage queue creation
* installs redis 5.0.5 from scl + enables the scl by default
* installs redis package from pypi
* installs docker + docker-compose
* nfs exports `/data/lsstdata`
* manages the `arc` user + `archive` group
* manages the `atadbot` user/group
* installs a sudo rule to allow members of the `comcam-archive-sudo` user group to `sudo` to role accounts without a passphrase
> initial comcam-arctl role

- site/profile/manifests/core/kubecompletion.pp
Noticed that the first run creates an empty file in /etc.bash_completion.d/kubectl, so I added an additional condition (and test it) to make sure it gets properly created.
> add condition for first run

- hieradata/org/ncsa/role/headerservice.yaml
- hieradata/site/nts.yaml
- site/profile/manifests/headerservice_conda.pp
- site/profile/manifests/sal.pp
Creates profile::headerservice_conda
for deploying headerservice directly from conda
still needed for testing new version before pushing to production
> Add profile::headerservice_conda

- hieradata/org/ncsa.yaml
- hieradata/org/ncsa/role/lhntest.yaml
- hieradata/site/nts/role/puppet_master.yaml
- site/profile/data/common.yaml
- site/profile/data/org/ncsa.yaml
- site/profile/manifests/ncsa/allow_ssh_from_bdc.pp
- site/profile/manifests/ncsa/lhn_target_from_bdc.pp
Creates a role and cluster for Long Haul Network (LHN) testing to nodes in the NCSA Test Stand.
- Add cluster lhntest
- Add level1_adm access to puppetmaster nodes in NTS
- Add profile::ncsa::allow_ssh_from_bdc (not actually used)
- Add role ncsa::lhntest
- Hieradata moved to ncsa::role::lhntest
- Move hieradata for profile::ncsa into org/ncsa
> Add profile::ncsa::lhn_target_from_bdc

- site/profile/manifests/core/icinga_agent.pp
- site/profile/manifests/core/icinga_master.pp
Now we can add an agent that doesn't belong to puppet (like switches or vmware clusters)
> IT-2427: icinga master as CA for icinga agents

- Puppetfile
- hieradata/site/ls/role/dnscache.yaml
```
[root@dns2 ~]# dig +short -x 139.229.136.32
spectator.lsst.local.
```
> forward 136.229.139.in-addr.arpa to crux (active directory)

- hieradata/org/lsst/role/foreman.yaml
To prevent management of the /etc/puppetlabs/code/environments/common
dir.
> undefine puppet::server_common_modules_path

- hieradata/site/cp/role/atarchiver.yaml
- hieradata/site/cp/role/atsdaq.yaml
- hieradata/site/cp/role/nfsserver.yaml
NFS permitted exports were pointing to the old IT Network, so the NFS mount couldn't proceed.
> IT-2487: change network 1621 for 1101

- hieradata/site/cp.yaml
Syslog was pointing to an obsolete destination on cp site, so no syslog are being fetch in neither graylog interfaces.
> IT-2498: update syslog destination

- Puppetfile
- hieradata/org/lsst/role/daq-mgmt.yaml
Create a new role for daq management only nodes.  At present, this is intended for the `atsdaq-mgmt` host but a dedicated daq management node for comcam is planned for the future.
> add daq-mgmt role

- hieradata/cluster/auxtel-ccs.yaml
- hieradata/cluster/comcam-ccs.yaml
- hieradata/cluster/pathfinder-ccs.yaml
- site/profile/files/ccs/profile_d/lsst-ccs.sh
Installs the rh-git218 package from the centos-release-scl-rh repository
> hiera: add rh-git218 to ccs clusters

- hieradata/node/comcam-arctl01.cp.lsst.org.yaml
- hieradata/node/comcam-mcm.cp.lsst.org.yaml
These hosts appear to be loosing their static dds routes when the dhcp configured dds interface bounces.
> change  comcam-arctl01 & comcam-mcm dds interface dhcp -> static ip

- hieradata/cluster/antu.yaml
Similar to changes already made for the andes cluster, the debug IPs are
to be removed.
> rm dds network debug IPs from antu cluster

- Puppetfile
This fetches rpms from nexus instead of slac.
> Bump ccs_sal module version to 0.5.0

- hieradata/site/tu/role/foreman.yaml
The pool is being reduced as more statically assigned IPs are needed.
> change vlan3040 dhcp pool to 140.252.146.90-94

- site/profile/manifests/docker.pp
Updates to prevent puppet firewall from removing NAT rules created by docker.
> IT-3024 update docker nat ignore rules for puppet firewall

- hieradata/org/lsst/role/archiver.yaml
- hieradata/org/lsst/role/atsccs.yaml
- hieradata/org/lsst/role/ccs-mcm.yaml
To resolve this error message:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Tmpfile[docker_tmp]: parameter 'filename' expects a match for Systemd::Dropin = Pattern[/^[^\/]+\.conf$/], got 'docker_tmp' (file: /etc/puppetlabs/code/environments/IT_3026_comcam_auxtel_software/site/profile/manifests/core/systemd.pp, line: 21) on node comcam-mcm.cp.lsst.org
> add .conf to systemd::tmpfile resource names

- hieradata/org/lsst/role/comcam-fp.yaml
- hieradata/org/lsst/role/daq-mgmt.yaml
- hieradata/site/tu/role/foreman.yaml
As this is a noop. Per `dhcpd.conf(5)`:
Note  that  the  most  specific scope for which the concept of authority makes any
sense is the physical network segment - either a  shared-network  statement  or  a
subnet  statement  that is not contained within a shared-network statement.  It is
not meaningful to specify that the server is authoritative for some subnets within
a  shared network, but not authoritative for others, nor is it meaningful to spec‐
ify that the server is authoritative for some host declarations and not others.
> remove "authoritative" statement from dhcp pools

- hieradata/site/dev/role/hypervisor.yaml
The value set in hiera was wrong and this was exposed by IT-1657
removing the unmanaged keys.
> (dev) fix hypervisor foreman ssh pubkey

- hieradata/cluster/chonchon.yaml
- hieradata/cluster/pillan.yaml
- hieradata/cluster/ruka-workers.yaml
- hieradata/cluster/ruka.yaml
- hieradata/cluster/vk8s.yaml
- hieradata/node/sal-dx.cp.lsst.org.yaml
- hieradata/org/lsst/role/icinga-master.yaml
- hieradata/org/lsst/role/rke.yaml
- hieradata/site/tu/cluster/rancher.yaml
In preparation for a planned batch security update.  To be replaced with
a global kernel versionlock.
> rm versionlocked kernel versions

- Puppetfile
- site/profile/data/org/lsst.yaml
Per https://github.com/puppetlabs/puppetlabs-yumrepo_core/blob/main/lib/puppet/type/yumrepo.rb#L41-L45, the `yumrepo` `target` parameter does not do anything.
> cleanup centos yum repo names

- hieradata/org/lsst/role/puppetdb.yaml
Note that puppetdb-termini is staying at 6.16.1.
> (puppetdb role) bump puppetdb to 6.18.0

- hieradata/org/ncsa.yaml
One line hiera change
`pakrat_client::default_snapshot: "2021-07-22-1626989101"`
to update the OS snapshot to the same as in IHS-4991
> IT-3127 NCSA OS snapshot 2021-07-22-1626989101

- Puppetfile
- hieradata/org/lsst/role/amor.yaml
- hieradata/org/lsst/role/ts-csc.yaml
- site/profile/manifests/core/docker.pp
- spec/classes/core/docker_spec.rb
- spec/hosts/roles/amor_spec.rb
- spec/hosts/roles/docker_compose_spec.rb
- spec/hosts/roles/ts_csc_spec.rb
To allow docker::networks::networks to be defined in hiera, as needed, without additional modification to the manifest.
> add docker::networks to profile::core::docker

- hieradata/cluster/comcam-ccs.yaml
- hieradata/node/comcam-fp01.tu.lsst.org.yaml
- hieradata/org/lsst/role/ccs-mcm.yaml
- hieradata/org/lsst/role/comcam-fp-tts.yaml
- hieradata/site/tu/cluster/comcam-ccs.yaml
- site/profile/manifests/ccs/daq_client.pp
- site/profile/templates/ccs/daq_client/daq.app.epp
- site/profile/templates/ccs/daq_client/daqvX-setup.epp
Changes related to Tucson test-stand. The only change that applies elsewhere is the one to hieradata/cluster/comcam-ccs.yaml, but it should be a no-op.
These changes should address most of the issues from
https://jira.lsstcorp.org/browse/IT-3277?jql=project%20%3D%20IT%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20tucson-test-stand%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC
> CCS changes for Tucson test-stand

- hieradata/node/comcam-fp01.tu.lsst.org.yaml
Since tonyj created /opt/lsst/ccs/prod/bin/h2db, we can now use a
standard service file for this.
> hiera: add the h2db service on comcam-fp01.tu

- Puppetfile
- hieradata/cluster/auxtel-ccs.yaml
- hieradata/cluster/comcam-ccs.yaml
- hieradata/site/tu/cluster/auxtel-ccs.yaml
- hieradata/site/tu/cluster/comcam-ccs.yaml
This version produces alerts when a ccs systemd service fails.
Add the corresponding hiera config for the alert email address.
> Bump ccs_software module version

- hieradata/org/ncsa.yaml
Affects nodes
- lsst-nts-ccheader.ncsa.illinois.edu
- lsst-nts.csc1.ncsa.illinois.edu
Change are tested and applied to the nodes. This merge just get's rid of the branch and allows moving the `ncsa_production` pointer forward.
> DM-32881 bump NCSA default OS snapshot

- hieradata/org/ncsa.yaml
Update docker version so puppet doesn't try to downgrade it.
Affects ncsa/role/puppet_master
> IT-3408 bump NCSA docker version to 20.10.11

- hieradata/node/dtn01.ls.lsst.org.yaml
- site/profile/manifests/core/dtn.pp
The `tql_tunning` service is being invoked on every puppet run.  This is
undesirable as it makes it appear if the puppet state on the node is
not converged.  Running interface tuning commands as a one-off is also
undesirable as parameters may be lost when the interface goes up and
down.  The NM dispatch script hooks are a more reliable option.
Additionally, interface name specific configuration generally should not
be baked into a profile class as it is inherently tied to a hosts
hardware.
> (profile::core::dtn) rm tql_tunning service; replace with NM dispatch

- hieradata/org/lsst/role/hexrot.yaml
- spec/hosts/roles/hexrot_spec.rb
http://cagvm3.ctio.noao.edu/nexus/repository/gpg-rpm/MSO/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: cagvm3.ctio.noao.edu; Unknown error"
Trying other mirror.
One of the configured repositories failed (Nexus GPG MSO Repository),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:
1. Contact the upstream for the repository and get them to fix the problem.
2. Reconfigure the baseurl/etc. for the repository, to point to a working
upstream. This is most often useful if you are using a newer
distribution release than is supported by the repository (and the
packages for the previous distribution release still work).
3. Run the command with the repository temporarily disabled
yum …
> (hexrot role) disable ctio nexus yum repos; hostname does not exist

- site/profile/manifests/core/hardware.pp
- site/profile/manifests/util/kernel_param.pp
- spec/classes/core/hardware_spec.rb
- spec/defines/util/kernel_param_spec.rb
Without forcing a reboot to apply this kernel parameter.  We aren't even sure yet if this will be a helpful change as, anecdotally, NVMe hotplug will always be unreliable on EL7.
> attempt to improve NVMe hotplug on Supermicro 1114S-WN10RT

- site/profile/manifests/core/docker.pp
- spec/classes/core/docker_spec.rb
In an attempt to fix the start up dep ordering problem where
`docker.socket` (yes, `docker.socket`, not `docker.server`) attempts to
start up before `sssd` is able to resolve group names from IPA. The fix
is to set docket.socket to use `root` as the group as `dockerd` will
chgrp the socket as startup anyways.  We then add a dep from
`docker.service` on `sssd.service` in an attempt to ensure that it is
possible to resolve the `docker` group via IPA.
> (profile::core::docker) start docker.service after sssd.service

- Puppetfile
This uses the CCS remote config server.
Ie, it adds to /etc/ccs/ccsGlobal.properties the line org.lsst.ccs.config.remote=true
> Bump ccs_software module to 1.0.1

- hieradata/cluster/auxtel-ccs.yaml
- hieradata/node/auxtel-fp01.cp.lsst.org.yaml
- hieradata/node/auxtel-mcm.cp.lsst.org.yaml
- hieradata/role/atshcu.yaml
The net effect is to add these missing settings to node auxtel-dc01.
I see auxtel nodes are currently on a non-standard branch, so either these changes need to eventually be applied to that branch, or the auxtel branch needs to be merged into production (if appropriate).
> hiera: move auxtel ccs udp_properties to a cluster-wide setting

- hieradata/node/comcam-fp01.cp.lsst.org.yaml
It just causes warnings.
Ref https://jira.lsstcorp.org/browse/IT-3814
> hiera: no longer set ccs_monit::temp for comcam-fp01

- site/profile/manifests/core/common.pp
- spec/classes/core/common_spec.rb
Remove the ifcfg- file created on some hosts by problems with the
foreman provisioning template.
The presence of `/etc/sysconfig/network-scripts/ifcfg-` file on hosts running `libvirt` was causing strange errors via the API. Removing this fix fixed the errors.
> (profile::core::common) rm ifcfg- file

- site/profile/manifests/core/puppet_master.pp
- spec/classes/core/puppet_master_spec.rb
A typo (missing >) is causing error emails to pile up in
/var/spool/mail/root.
> (profile::core::puppet_master) fix cron /dev/null redirects

- hieradata/role/rke.yaml
- site/profile/data/common.yaml
- spec/classes/core/debugutils_spec.rb
- spec/hosts/roles/foreman_spec.rb
- spec/hosts/roles/rke_spec.rb
- spec/spec_helper.rb
Migrate jq package into profile::core::debugutils from the rke role to make it more widely available.
> (profile::core::debugutils) add jq package

- Puppetfile
- hieradata/common.yaml
- hieradata/site/cp/role/hvac.yaml
- site/profile/manifests/core/ipa.pp
- spec/classes/archive/commmon_spec.rb
- spec/classes/core/common_spec.rb
- spec/classes/core/ipa_spec.rb
- spec/hosts/roles/amor_spec.rb
- spec/hosts/roles/atsccs_spec.rb
- spec/hosts/roles/atsdaq_spec.rb
- spec/hosts/roles/auxtel_archiver_spec.rb
- spec/hosts/roles/ccs_dc_spec.rb
- spec/hosts/roles/comcam_archiver_spec.rb
- spec/hosts/roles/comcam_fp_spec.rb
- spec/hosts/roles/daq_mgt_spec.rb
- spec/hosts/roles/docker_compose_spec.rb
- spec/hosts/roles/dtn_spec.rb
- spec/hosts/roles/foreman_spec.rb
- spec/hosts/roles/forwarder_spec.rb
- spec/hosts/roles/generic_spec.rb
- spec/hosts/roles/hexrot_spec.rb
- spec/hosts/roles/hvac_spec.rb
- spec/hosts/roles/icinga_master_spec.rb
- spec/hosts/roles/m2_spec.rb
- spec/hosts/roles/rke_spec.rb
- spec/hosts/roles/ts_csc_spec.rb
- spec/spec_helper.rb
The first puppet agent run on a newly provisioned hosts was failing due to auth configuration related resources attempting to sync prior to the `ipa-client-install` script having been run.
> fix ipa client setup order of operations

- site/profile/manifests/core/ipa.pp
- spec/classes/core/docker_spec.rb
- spec/classes/core/ipa_spec.rb
- spec/classes/ts/opensplicedds_spec.rb
- spec/fixtures/hiera-profile-mod.yaml
- spec/fixtures/hieradata/profile-only.yaml
- spec/spec_helper.rb
Unit tests of profile classes were, in some cases surprisingly, being effected by production hiera hierarchy data.  This is fixed by using a more limited fixtured hiera configuration by default and while the previous default fixtured hiera configuration is used only for example groups labeled with `:site`, Currently, only host/role specs are using `:site`.
> decouple profile mod spec from production hiera data

- Puppetfile
This uses an explicit alternative for the java commands,
rather than relying on priority (which can be fragile).
> Bump ccs java_artisanal version to 2.2.1

- site/profile/manifests/ccs/common.pp
This installs maven 3.6.3 in /opt and makes it the default.
> Install newer maven on CCS hosts

- hieradata/common.yaml
- spec/spec_helper.rb
The current syntax is nonsense.  There is no `versionlock` param on the
`yum::plugin` class to pass a hash into.
based on:
-#610
> (common) fix setting of yum::plugin::versionlock::clean param

- Puppetfile
No change in functionality. This is migrating from a git tag to an official release.
> (Puppetfile) bump puppet/telegraf to 4.2.0

- Puppetfile
No change in functionality. This is migrating from a git tag to an official release.
> (Puppetfile) bump saz/timezone to 6.2.0

- Puppetfile
No change in functionality. This is migrating from a git tag to an official release.
> (Puppetfile) bump puppetlabs/tomcat to 6.2.0

- Puppetfile
No change in functionality. This is migrating from a git tag to an official release.
> (Puppetfile) bump puppet/augeasproviders_grub to 4.0.0

- spec/hosts/roles/catchall_spec.rb
As a performance optimization, test with only one site.  If it is
important that a role is better tested, it should have its own spec
file.
> (spec) reduce role catchall to one site per OS at random

- Puppetfile
The 6.0.0 release includes https://github.com/voxpupuli/puppet-rsyslog/pull/186
> (Puppetfile) bump puppet/rsyslog to 6.0.0

- Puppetfile
> (Puppetfile) bump lsst/dellperc to 1.1.0

- Puppetfile
- hieradata/cluster/auxtel-ccs.yaml
- hieradata/cluster/comcam-ccs.yaml
- hieradata/cluster/pathfinder-ccs.yaml
The FQDN entry should be there by default, but the upstream hosts module has a long-standing bug:
https://github.com/ghoneycutt/puppet-module-hosts/issues/40
This change switches to an lsst-it fork of the module, which adds this pull request:
https://github.com/ghoneycutt/puppet-module-hosts/pull/63
This fixes adding the FQDN entry, if stored_config = false (it is true by default).
It is set false only on CCS clusters (though I can't see why it should not be so everywhere).
Ref: https://jira.lsstcorp.org/browse/IT-3889
Note:
This uses the branch IT-3889/fqdn of lsst-it/puppet-module-hosts.
That probably isn't the right way to do it.
Maybe there should be an "lsst_production" (or somesuch) branch in that repo?
> Add FQDN entry to /etc/hosts on CCS clusters

- metadata.json
As we have officially migrated to puppet7.
> (metadata.json) drop puppet6 support

- hieradata/common.yaml
- hieradata/role/foreman.yaml
- hieradata/role/ipareplica.yaml
- hieradata/role/perfsonar.yaml
- hieradata/role/puppetdb.yaml
- site/profile/data/common.yaml
- site/profile/manifests/core/kernel.pp
- spec/classes/core/kernel_spec.rb
- spec/classes/core/yum_spec.rb
- spec/hosts/roles/amor_spec.rb
- spec/hosts/roles/comcam_archiver_spec.rb
- spec/hosts/roles/docker_compose_spec.rb
- spec/hosts/roles/foreman_spec.rb
- spec/hosts/roles/hexrot_spec.rb
- spec/hosts/roles/ipareplica_spec.rb
- spec/hosts/roles/perfsonar_spec.rb
- spec/hosts/roles/puppetdb_spec.rb
- spec/hosts/roles/rke_spec.rb
- spec/hosts/roles/ts_csc_spec.rb
- spec/spec_helper.rb
The semantics of the yum versionlock plugin changed between EL7 and EL8.  The `yum::versionlock` defined type added new parameters in order to be compatible with EL8+.  The new parameters are backwards compatible with EL7.
> update to modern yum::versionlock api 

- Puppetfile
- hieradata/common.yaml
- site/profile/data/common.yaml
- site/profile/manifests/core/docker.pp
- spec/classes/core/docker_spec.rb
- spec/hosts/roles/foreman_spec.rb
- spec/spec_helper.rb
Presently, all roles are using the same docker version.  Removing the hiera keys from the common hierarchy and relying the defaults is both DRYing and removes versionlocks which will have to be updated and maintained for EL8.
> docker cleanup/update

- Puppetfile
- hieradata/role/rke.yaml
- spec/hosts/roles/rke_spec.rb
The existing `kubectl` method uses a Google provided yum repo and rpm to install kubectl.  Google does not provide an equivalent repo for EL8.  Although, the same binary/rpm should work on EL8, it would be ugly to configuring an EL7 yum repo across multiple EL major versions. As a more distribution agnostic approach, the `lsst/kubectl` puppet module downloads and installs official k8s `kubectl` binary releases.
> replace inline kubectl install code with lsst/kubectl mod

- .rubocop.yml
- hieradata/node/tel-hw1.tu.lsst.org.yaml
- hieradata/node/tel-lt1.tu.lsst.org.yaml
- site/profile/manifests/ccs/krb5_token.pp
- site/profile/manifests/core/common.pp
- site/profile/manifests/core/ipa_pwd_reset.pp
- site/profile/manifests/core/keytab.pp
- site/profile/manifests/core/rke.pp
- site/profile/manifests/util/keytab.pp
- spec/classes/core/common_spec.rb
- spec/classes/core/ipa_pwd_reset_spec.rb
- spec/classes/core/keytab_spec.rb
- spec/classes/core/rke_spec.rb
- spec/defines/util/keytab_spec.rb
- spec/fixtures/hieradata/common.yaml
- spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
- spec/hosts/nodes/tel-lt1.tu.lsst.org_spec.rb
Additionally, krb5 keytab values have been converted from `String` to `Sensitive[String]` as a first step towards more considerate handling of secrets.
See: https://puppet.com/docs/puppet/7/securing-sensitive-data.html
Related to https://github.com/lsst-it/lsst-puppet-hiera-private/pull/75
> allow ssh between saluser@tel-lt1.tu and saluser@tel-hw1.tu

- Puppetfile
- hieradata/role/rke.yaml
- site/profile/manifests/core/rke.pp
- spec/classes/core/rke_spec.rb
- spec/hosts/roles/rke_spec.rb
- spec/spec_helper.rb
This mod provides the `net.bridge.bridge-nf-call-iptables` sysctl, which
rke requires be set to a value different than the default.  It seems
that this kmod often isn't loaded until dockerd starts up. This was
causing an order of operations issue with setting
the`net.bridge.bridge-nf-call-iptables` sysctl.
> (rke role) ensure br_netfilter kmod is loaded

- Gemfile
To resolve this error caused by the rspec-github gem:
SyntaxError: /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'
@output.info(@subject, ...)
^
> (Gemfile) pin console gem version to 1.15.x

- hieradata/role/dnscache.yaml
- spec/hosts/roles/dnscache_spec.rb
On EL8, severity level of `info` was causing all queries to be logged.
> (dnscache role) change default bind logging to `notice`

- Puppetfile
- site/profile/manifests/core/common.pp
- spec/classes/core/common_spec.rb
- spec/default_facts.yml
The `simp/auditd` mod includes a default set of auditd rules which appear to be a reasonable starting point.
> manage auditd rules

- hieradata/role/amor.yaml
- hieradata/role/docker-compose.yaml
- hieradata/role/hexrot.yaml
- hieradata/role/ts-csc.yaml
- site/profile/manifests/core/docker/compose.pp
- spec/classes/core/docker/compose_spec.rb
- spec/hosts/roles/amor_spec.rb
- spec/hosts/roles/docker_compose_spec.rb
- spec/hosts/roles/hexrot_spec.rb
- spec/hosts/roles/ts_csc_spec.rb
Instead of manual installation of `docker-compose` using pip.
To resolve this error:
Error: 'pip3 --log /tmp/pip.log install     docker-compose==1.25.0' returned 1 instead of one of [0]
Error: /Stage[main]/Python/Python::Pip[docker-compose]/Exec[pip_install_docker-compose]/returns: change from 'notrun' to ['0'] failed: 'pip3 --log /tmp/pip.log install     docker-compose==1.25.0' returned 1 instead of one of [0] (corrective)
> (docker-compose role) use docker-compose package

- hieradata/node/perfsonar1.ls.lsst.org.yaml
Routes to SLAC were added to perfsonar1.ls as requested in Ticket IT-3892
SLAC Perfsonar:
Psnr-oct-v40 134.79.235.226
Psnr-oct-v41 134.79.235.242
> (perfsonar1.ls) add SLAC routes

- .github/workflows/rake_checks.yaml
The gha run time is already > 10 minutes with only two OS in the test matrix (EL7 & EL8) when using the default gha runner.  It is hoped that switching to the 16c runner will reduce the time for all gha workflows to run to < 10 minutes.
> (gha) switch to 16 core runner

- Puppetfile
To pickup AlmaLinux 9 support.
Depends upon:
-  https://github.com/lsst-it/puppet-java_artisanal/pull/13
- #699
> (Puppetfile) bump puppet/yum to 6.1.0

- site/profile/data/common.yaml
- site/profile/data/osfamily/RedHat/major/7.yaml
- site/profile/data/osfamily/RedHat/major/8.yaml
- site/profile/data/osfamily/RedHat/major/9.yaml
- spec/spec_helper.rb
The currently pinned version, 20.10.12, does not have packages for EL9.
We are updating to a version that has packages for EL7, EL8, & EL9.
Based on #702
> bump docker to 20.10.21

- hieradata/cluster/auxtel-ccs.yaml
- hieradata/cluster/auxtel-ccs/osfamily/RedHat/major/7.yaml
- hieradata/cluster/comcam-ccs.yaml
- hieradata/cluster/comcam-ccs/osfamily/RedHat/major/7.yaml
- hieradata/role/foreman.yaml
- hieradata/role/foreman/osfamily/RedHat/major/7.yaml
- hieradata/role/foreman/osfamily/RedHat/major/8.yaml
- hieradata/role/ipareplica.yaml
- hieradata/role/ipareplica/osfamily/RedHat/major/7.yaml
- hieradata/role/ipareplica/osfamily/RedHat/major/8.yaml
- hieradata/role/perfsonar.yaml
- hieradata/role/perfsonar/osfamily/RedHat/major/7.yaml
- hieradata/role/perfsonar/osfamily/RedHat/major/8.yaml
- hieradata/role/puppetdb.yaml
- hieradata/role/puppetdb/osfamily/RedHat/major/7.yaml
- hieradata/role/puppetdb/osfamily/RedHat/major/8.yaml
- spec/hosts/roles/ipareplica_spec.rb
Based on:
- #604 
- #605 
- #608 
- #610 
- #614 
- #622 
- #623 
- #627 
- #639 
- #642 
- #643 
- #644
- #645 
- #646
- #647 
- #648 
- #654
- #659 
- #660 
- #662 
- #667 
- #670 
- #672 
- #673 
- #674 
- #675 
- #676 
- #679 
- #680 
Roles tested as working on EL8:
- generic
- dnscache
- rke
> [the last part of] initial el8 / almalinux support

- site/profile/manifests/core/rke.pp
- spec/classes/core/rke_spec.rb
- spec/spec_helper.rb
The class level require was effectively blocking the docker class resources if easy_ipa fails to install.  Instead of the entire class requiring easy_ipa, we are adding the require metaparam to two resources that need ipa user name resolution to be functioning.
> (profile::core::rke) drop class level require of easy_ipa

- site/profile/data/common.yaml
As this package isn't present on EL9 and it is unclear if we have ever used this package.
> (profile::core::debugutils) drop tuned-utils-systemtap package

- hieradata/role/rke.yaml
- hieradata/role/rke/osfamily/RedHat/major/7.yaml
- hieradata/role/rke/osfamily/RedHat/major/8.yaml
- spec/hosts/roles/rke_spec.rb
There does not [yet] appear to be a clustershell package in EPEL9.
> (rke role) restrict inclusion of clustershell class to EL7/EL8

- hieradata/common.yaml
- hieradata/common/osfamily/RedHat/major/9.yaml
- hieradata/site/cp.yaml
- hieradata/site/dev.yaml
- hieradata/site/ls.yaml
- hieradata/site/tu.yaml
There are no freely available official packages built/published for EL9 as icinga has decided to place them behind a paywall.  We need to consider if we want to build our own rpms from source, license icinga, or migrate to a different solution. In the meantime, we need to disable attempting to manage icinga on EL9 via puppet.
See: https://github.com/Icinga/icinga2/issues/9390
Based on #704
> disable icinga on EL9

- hieradata/role/rke/osfamily/RedHat/major/9.yaml
- site/profile/manifests/core/common.pp
- spec/spec_helper.rb
This change will enable NetworkManager support on EL9 nodes by default. The current scheme requires each role to "opt-in" to NM support.
> (profile::core::common) enable NetworkManager support on EL9 by default

- hieradata/role/rke.yaml
- hieradata/role/rke/osfamily/RedHat/major/7.yaml
- hieradata/role/rke/osfamily/RedHat/major/8.yaml
- spec/hosts/roles/rke_spec.rb
Clustershell is now available via EPEL9.
> (rke role) install clustershell on EL9

- hieradata/node/dns2.cp.lsst.org.yaml
as requested on ticket IT-4214, the default route of the dns2 is set to Rubin network instead of rojas net link. (139.229.160.54)
> (dns2.cp) change default route rubins network

- Puppetfile
Resolves this error:
```
Error: Execution of '/bin/dnf -d 0 -e 1 -y install telegraf' returned 1: The GPG keys listed for the "InfluxData Repository - AlmaLinux 8" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: telegraf-1.25.1-1.x86_64
GPG Keys are configured as: https://repos.influxdata.com/influxdb.key
Error: GPG check FAILED
Error: /Stage[main]/Telegraf::Install/Package[telegraf]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/dnf -d 0 -e 1 -y install telegraf' returned 1: The GPG keys listed for the "InfluxData Repository - AlmaLinux 8" repository are already installed but they are not correct for this package.
Check that the correct key URLs are …
```
> fix telegraf package gpgkey error

- .github/workflows/librarian_puppet.yaml
- .github/workflows/markdownlint.yaml
- .github/workflows/rake_checks.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/yamllint.yaml
To resolve this warning in the gha out put:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> fix "Node.js 12 actions are deprecated." warning to gha logs

- site/profile/manifests/core/sysctl/rp_filter.pp
- spec/classes/core/sysctl/rp_filter_spec.rb
Testing has shown that setting `net.ipv4.conf.p2p1/2505.rp_filter` to
`0` has no effect if `net.ipv4.conf.all.rp_filter` is set to `1`. Thus,
we need to also change the value of `net.ipv4.conf.all.rp_filter` when
modifying the other interfaces. For good measure,
`net.ipv4.conf.default.rp_filter` is also set to match
`net.ipv4.conf.all.rp_filter` to handle any newly created interfaces.
> (proflie::core::sysctl::rp_filter) add 'all' & 'default' to dev list

- hieradata/cluster/manke.yaml
- hieradata/cluster/pillan.yaml
- hieradata/cluster/ruka.yaml
- hieradata/site/tu/role/foreman.yaml
- spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
- spec/hosts/roles/foreman_spec.rb
Note that these bare metal nodes still have static routes configured for dds subnets:
- comcam-archiver.tu.lsst.org
- auxtel-archiver.tu.lsst.org
- comcam-mcm.tu.lsst.org
- love1.tu.lsst.org
- tel-hw1.tu.lsst.org
- auxtel-mcm.tu.lsst.org
It appears that `dhclient` on EL7 does not handle dhcp option 121 by default.
> (site/tu) enable dhcp static routes for dds subnets

- hieradata/site/tu/role/foreman.yaml
- spec/hosts/roles/foreman_spec.rb
The laserlab subnet was running out of assignable IPs. The dhcp pool is being reduced by 2 (to a total of 3 IPs) to make room for new dhcp reservations.
> (site/tu/role/foreman) reduce laserlab dhcp pool

- hieradata/site/dev/role/foreman.yaml
- hieradata/site/ls/role/foreman.yaml
- hieradata/site/tu/role/foreman.yaml
- spec/hosts/roles/foreman_spec.rb
The `{dev,tu,ls}_production` envs are to be replaced with `production`.
The `cp_production` env is still retained for use at the summit.
Based on #753
> (role/foreman) retire {dev,tu,ls}_production env name
